services:
  worker:
    build:
      target: worker-gpu
    image: ogniskowy-grajek-worker-gpu:${APP_VERSION:-dev}
    environment:
      AUDIO_DEVICE: auto
      ASR_DEVICE: cuda
    devices:
      - "nvidia.com/gpu=all"
