[server]
headless = true
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501
baseUrlPath = "ogniskowy-grajek"
maxUploadSize = 1

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff9f1c"
backgroundColor = "#111318"
secondaryBackgroundColor = "#20242c"
textColor = "#f5f1e8"
